### PR TITLE
Made httpDecorators accept route as an argument

### PR DESCRIPTION
**Pull request by pamidur**
Added shortcuts for route decorator by using argument in http*

Example
```js
export default class DataController{

    // so this
    @httpGet('getdata/:id')
    getdata(id){
        this.send({ saved: 0 });
    }    

    // equals to this
    @httpGet
    @route('getdata/:id')
    getdata(id){
        this.send({ saved: 0 });
    }     
}
```

### CODE REVIEW

**Comment by arackaf** [comment]
@pamidur just taking a quick look for now, but can you explain this?

if(regVerb == 'delete') regVerb = 'del';
           request[regVerb](uri, {}, function (error, response, obj) {

Was that a bug in my prior code?  Are deletes supposed to be keyed as "del" in express?

**Comment by pamidur** [comment]
Not express, you're using request.js v2.64.0. 
https://github.com/request/request/blob/v2.64.0/index.js

> ```js 
> // define like this to please codeintel/intellisense IDEs
> request.get = verbFunc('get')
> request.head = verbFunc('head')
> request.post = verbFunc('post')
> request.put = verbFunc('put')
> request.patch = verbFunc('patch')
> request.del = verbFunc('del')
> ```

And there should be 'del' verb for it to work correctly

**Comment by arackaf** [comment]
Ah gotcha!  Very good then. 

I'll try to merge this tomorrow.  Thanks a ton for all your help here!

**Comment by pamidur** [comment]
Thank you for creating great tool. Looking forward to seeing new version on npm.

**Comment by arackaf** [comment]
Merged.  VERY clever way to handle the decorator being used either way.  Once Babel 7 drops with the updated decorator proposal I'll have to update that code, but that should be straightforward, and certainly not something to worry about now.

Thanks a ton for all your contributions.

Sometime this weekend I'll get rid of Karma, update the docs, and get this released as 1.0

**Comment by arackaf** [comment]
By the way - are you on Twitter by chance?

**Comment by pamidur** [comment]
Not really :) I do have an account but barely use it.
You can reach me via skype:senior.pamidur if anything.

**Comment by arackaf** [comment]
@pamidur I've updated the docs quite a bit - if you'd like to take a look, I'd be eager to hear any feedback you might have.

Also, I'll definitely list and credit you before I release this as 1.0 - you want me to use your Twitter handle to identify you? Your GitHub profile?

**Comment by pamidur** [comment]
I went through doc. It's pretty straightforward. Though I'd put a big **bold** highlight at the very beginning about using destructure for params access, cause I did that mistake a few times already :)

Another thing is that it would be cool to have JSDoc for "public" methods like this 

```js
/**
 * Marks method to accessible via PATCH verb
 * @param {string} routeName Specifies roure override for this method
 */
function httpPatch(routeName) {
    return _applyUniversalHttpDecorator('patch', routeName, arguments);
}
```

So this help IDE and devs
image

Please use my github profile.

**Comment by pamidur** [comment]
One more example
```js
/**
 * Gets through folder tree and registers every controller found
 * @param {express} app 
 * @param {Object} config Config how we find controllers
 * @param {function} config.fileTest configures file test
 * @param {string} config.controllerPath configures where to find controllers
 * @param {*} _overrides 
 */
function createAllControllers(app, config, _overrides) {
```

**Comment by arackaf** [comment]
+1 - thanks!

**Comment by pamidur** [comment]
Any ETA on npm version?

**Comment by arackaf** [comment]
Working on it - sorry.  It's code complete, just trying to find time to tweak the docs some more, add jsdoc comments, etc.

If you're just wanting to use it, just pull down the beta that's up on npm now.   It has all your new changes.

**Comment by arackaf** [comment]
@pamidur More docs tweaks, and a few simplifications added.  Will run through once more today or tomorrow and push out a 1.0.  

Feel free to shoot me any final feedback you might find.  (also, I've simplified the imports - you can now just `import {createAllControllers}` rather than going through that silly `easyControllers` object I had before (though I've left it for backward compat. 

And of course this is all on npm under a beta version, so feel free to use as desired.

**Comment by arackaf** [comment]
@pamidur - so sorry - forgot to give you credit in the docs - will update tomorrow.

**Comment by arackaf** [comment]
@pamidur I feel terrible to have forgotten yet again after writing the above, but it IS updated on npm now.  Thanks again!

**Comment by pamidur** [comment]
No worries, I was really happy to contribute to your great project. I use it for my projects now :)

**Pull request merged**
